# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multiplucker.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pythonosc.udp_client import SimpleUDPClient

ip = "127.0.0.1"
port = 5005

client = SimpleUDPClient(ip, port)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 488)
        self.g_melody = []
        self.b_melody = []
        self.e_melody = []
        self.duration_indefinite = -999
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 50, 131, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 160, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 200, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 240, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 120, 55, 16))
        self.label_5.setObjectName("label_5")
        self.speed_g_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.speed_g_edit.setGeometry(QtCore.QRect(240, 160, 101, 22))
        self.speed_g_edit.setObjectName("speed_g_edit")
        self.speed_b_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.speed_b_edit.setGeometry(QtCore.QRect(240, 200, 101, 22))
        self.speed_b_edit.setObjectName("speed_b_edit")
        self.speed_e_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.speed_e_edit.setGeometry(QtCore.QRect(240, 240, 101, 22))
        self.speed_e_edit.setObjectName("speed_e_edit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 120, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(150, 120, 71, 16))
        self.label_7.setObjectName("label_7")
        self.note_g_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.note_g_edit.setGeometry(QtCore.QRect(130, 160, 101, 22))
        self.note_g_edit.setObjectName("note_g_edit")
        self.note_b_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.note_b_edit.setGeometry(QtCore.QRect(130, 200, 101, 22))
        self.note_b_edit.setObjectName("note_b_edit")
        self.note_e_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.note_e_edit.setGeometry(QtCore.QRect(130, 240, 101, 22))
        self.note_e_edit.setObjectName("note_e_edit")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(350, 280, 93, 28))
        self.start_button.setObjectName("start_button")
        self.start_button.clicked.connect(lambda: self.start_string("all"))
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setGeometry(QtCore.QRect(450, 280, 93, 28))
        self.pause_button.setObjectName("pause_button")
        self.calibrate_button = QtWidgets.QPushButton(self.centralwidget)
        self.calibrate_button.setGeometry(QtCore.QRect(510, 50, 93, 28))
        self.calibrate_button.setObjectName("calibrate_button")
        self.melody_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.melody_all_button.setGeometry(QtCore.QRect(550, 280, 93, 28))
        self.melody_all_button.setObjectName("melody_all_button")
        self.pause_button_g = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button_g.setGeometry(QtCore.QRect(450, 160, 93, 28))
        self.pause_button_g.setObjectName("pause_button_g")
        self.pause_button_g.clicked.connect(self.pause_sequence)
        self.start_button_g = QtWidgets.QPushButton(self.centralwidget)
        self.start_button_g.setGeometry(QtCore.QRect(350, 160, 93, 28))
        self.start_button_g.setObjectName("start_button_g")
        self.start_button_g.clicked.connect(lambda: self.start_string("g"))
        self.pause_button_B = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button_B.setGeometry(QtCore.QRect(450, 200, 93, 28))
        self.pause_button_B.setObjectName("pause_button_B")
        self.pause_button_B.clicked.connect(self.pause_sequence)
        self.start_button_b = QtWidgets.QPushButton(self.centralwidget)
        self.start_button_b.setGeometry(QtCore.QRect(350, 200, 93, 28))
        self.start_button_b.setObjectName("start_button_b")
        self.start_button_b.clicked.connect(lambda: self.start_string("b"))
        self.pause_button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button_4.setGeometry(QtCore.QRect(450, 240, 93, 28))
        self.pause_button_4.setObjectName("pause_button_4")
        self.pause_button_4.clicked.connect(self.pause_sequence)
        self.start_button_e = QtWidgets.QPushButton(self.centralwidget)
        self.start_button_e.setGeometry(QtCore.QRect(350, 240, 93, 28))
        self.start_button_e.setObjectName("start_button_e")
        self.start_button_e.clicked.connect(lambda: self.start_string("e"))
        self.melody_e = QtWidgets.QPushButton(self.centralwidget)
        self.melody_e.setGeometry(QtCore.QRect(550, 240, 93, 28))
        self.melody_e.setObjectName("melody_e")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 120, 81, 16))
        self.label_9.setObjectName("label_9")
        self.melody_g = QtWidgets.QPushButton(self.centralwidget)
        self.melody_g.setGeometry(QtCore.QRect(550, 160, 93, 28))
        self.melody_g.setObjectName("melody_g")
        self.melody_b = QtWidgets.QPushButton(self.centralwidget)
        self.melody_b.setGeometry(QtCore.QRect(550, 200, 93, 28))
        self.melody_b.setObjectName("melody_b")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(380, 120, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(480, 120, 55, 16))
        self.label_10.setObjectName("label_10")
        self.message_text = QtWidgets.QTextEdit(self.centralwidget)
        self.message_text.setGeometry(QtCore.QRect(130, 320, 511, 101))
        self.message_text.setObjectName("message_text")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 350, 61, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(460, 50, 71, 16))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Multi-plucker UI"))
        self.label_2.setText(_translate("MainWindow", "G:"))
        self.label_3.setText(_translate("MainWindow", "B:"))
        self.label_4.setText(_translate("MainWindow", "E:"))
        self.label_5.setText(_translate("MainWindow", "Strings:"))
        self.label_6.setText(_translate("MainWindow", "Speed"))
        self.label_7.setText(_translate("MainWindow", "Note (MIDI)"))
        self.start_button.setText(_translate("MainWindow", "Start All"))
        self.pause_button.setText(_translate("MainWindow", "Pause All"))
        self.calibrate_button.setText(_translate("MainWindow", "Calibrate"))
        self.melody_all_button.setText(_translate("MainWindow", "Melody All"))
        self.pause_button_g.setText(_translate("MainWindow", "Pause (G)"))
        self.start_button_g.setText(_translate("MainWindow", "Start (G)"))
        self.pause_button_B.setText(_translate("MainWindow", "Pause (B)"))
        self.start_button_b.setText(_translate("MainWindow", "Start (B)"))
        self.pause_button_4.setText(_translate("MainWindow", "Pause (E)"))
        self.start_button_e.setText(_translate("MainWindow", "Start (E)"))
        self.melody_e.setText(_translate("MainWindow", "Melody (E)"))
        self.label_9.setText(_translate("MainWindow", "Melody Start"))
        self.melody_g.setText(_translate("MainWindow", "Melody (G)"))
        self.melody_b.setText(_translate("MainWindow", "Melody (B)"))
        self.label_8.setText(_translate("MainWindow", "Start"))
        self.label_10.setText(_translate("MainWindow", "Pause"))
        self.message_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Message:"))
        self.label_12.setText(_translate("MainWindow", "Reset:"))

    def update_message(self, message):
        self.message_text.append(message)
    
    def start_string(self, string):
        if string == "g":
            g_string = [[int(self.note_g_edit.text()), int(self.duration_indefinite), int(self.speed_g_edit.text()), 0.0]]
            self.update_message("Starting G String...")
            self.update_message(str(g_string))
            self.send_to_udp(g_string)
        if string == "b":
            b_string = [[int(self.note_b_edit.text()), int(self.duration_indefinite), int(self.speed_b_edit.text()), 0.0 ]]
            self.update_message("Starting B String...")
            self.update_message(str(b_string))
            self.send_to_udp(b_string)
        if string == "e":
            e_string = [[int(self.note_e_edit.text()), int(self.duration_indefinite), int(self.speed_e_edit.text()), 0.0]]
            self.update_message("Starting E String...")
            self.update_message(str(e_string))
            self.send_to_udp(e_string)
        if string == "all":
            self.update_message("Starting All Strings...")

    def pause_sequence(self, string):
        pass
    
    def get_array(self, arr):
        pass
    
    def send_to_udp(self, arr):
        print(f"Sending message to /Start: {arr}")
        client.send_message("/Start", arr)
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
